services:
  spring-app:
    build: .
    ports:
      - "8080:8080"

  mysql-db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sherlock
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE